baseURL = "https://pissedemu.github.io/"
defaultContentLanguage = "en"
languageCode = "en"

title = "PissedEmu"
theme = "gokarna"
publishDir = "docs"
enableRobotsTXT = true

[params]
  avatarURL = "/images/avatar.png"
  avatarSize = "size-l"
  description = "Number #1 no lifes OCE, very good this not normally :)"
  accentColor = "##f9b54c"
  metaKeywords = ["ctf", "australia", "cool"]
  footer = "PissedEmu"

  socialIcons = [
      {name = "twitter", url = "https://twitter.com/PissedEmu"},
      {name = "facebook", url = "https://ctftime.org/team/160273"}, # need ctftime svg
    ]

[permalinks]
  posts = "/:title"

[menu]
#  [[menu.main]]
#    identifier = "posts"
#    url = "/posts/"
#    pre = ""
#    post = ""
#    name = "Posts"
#    weight = 1
  
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 2

  [[menu.main]]
    identifier = "members"
    name = "Members"
    url = "/members"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 4
